# Generated by Django 4.1.7 on 2023-03-26 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='transport',
        ),
        migrations.AddField(
            model_name='saloon',
            name='transport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='transport_seats', to='core.transport', verbose_name='Транспорт'),
            preserve_default=False,
        ),
    ]
